### ISSUE TITLE
Installing JSC on windows fails

### ISSUE THREAD

**Issue by rbuckton** [devsnek/esvu#16]
```
JavaScriptCore ❯ Checking version...
esvu ✖ Fatal error installing JavaScriptCore TypeError: Cannot read property '1' of null
    at Function.resolveVersion (...\node_modules\esvu\src\engines\javascriptcore.js:56:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.install (...\node_modules\esvu\src\installer.js:43:21)
    at async installEngine (...\node_modules\esvu\src\bin.js:120:3)
    at async updateAll (...\node_modules\esvu\src\bin.js:148:7)
    at async main (...\node_modules\esvu\src\bin.js:168:7)
```

The link to the builds below no longer works: https://github.com/devsnek/esvu/blob/b85e51d383bd04a5f81e919d0413af882fca2122/src/engines/javascriptcore.js#L53

Apparently the site is now an SPA, but the upside is there is an API now:
- `https://build.webkit.org/api/v2/builders` returns a list of builders
- You can request builder info from `https://build.webkit.org/api/v2/builders/{builder}`
- You can request builds using `https://build.webkit.org/api/v2/builders/{builder}/builds?limit=200&order=-number&property=owners&property=workername&property=got_revision&property=identifier`

It looks like the builders `esvu` depends on are:
- `Apple-Win-10-Release-Build` (for `win32`) - builder: `67`
- `WinCairo-64-bit-WKL-Release-Build` (for `win64`) - builder: `27`
- `Apple-Catalina-Release-Build` (for `darwin64`) - builder: `54`

Example output for builder `27` looks like this (https://build.webkit.org/api/v2/builders/27/builds?limit=20&order=-number&property=owners&property=workername&property=got_revision&property=identifier):
```jsonc
{
  "builds": [
    {
      "builderid": 27,
      "buildid": 28081,
      "buildrequestid": 44548,
      "complete": true,
      "complete_at": 1614293446,
      "masterid": 1,
      "number": 740,
      "properties": {
        "got_revision": [
          "273514",
          "CheckOutSource"
        ],
        "identifier": [
          "234589@main",
          "Unknown"
        ],
        "owners": [
          [
            "tsavell@apple.com"
          ],
          "Build"
        ],
        "workername": [
          "wincairo-wkl-release-build-01",
          "Worker"
        ]
      },
      "results": 0,
      "started_at": 1614293271,
      "state_string": "build successful",
      "workerid": 31
    },
    ...
]
```

Per the build steps, what gets published to s3 is a zip using `.builds[0].properties.got_revision[0]` (in this case, `273514`), which you can see from the "transfer to s3" step at https://build.webkit.org/#/builders/27/builds/740

**Comment by devsnek** [comment]
@rbuckton could you check that this is working on windows now?

**Comment by QC-L** [comment]
```bash
esvu ✖ Fatal error installing JavaScriptCore TypeError: Cannot read property '1' of null
    at Function.resolveVersion (/Users/qc-l/.nvm/versions/node/v12.16.3/lib/node_modules/esvu/src/engines/javascriptcore.js:62:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.install (/Users/qc-l/.nvm/versions/node/v12.16.3/lib/node_modules/esvu/src/installer.js:43:21)
    at async installEngine (/Users/qc-l/.nvm/versions/node/v12.16.3/lib/node_modules/esvu/src/bin.js:120:3)
    at async updateAll (/Users/qc-l/.nvm/versions/node/v12.16.3/lib/node_modules/esvu/src/bin.js:148:7)
    at async main (/Users/qc-l/.nvm/versions/node/v12.16.3/lib/node_modules/esvu/src/bin.js:168:7)
```

I'm having the same problem on my Mac. @devsnek

**Comment by devsnek** [comment]
@QC-L can you test with the master version of this repo? `npm i -g devsnek/esvu`.

@rbuckton ping again for windows

**Comment by QC-L** [comment]
@devsnek Let me try it

**Comment by rwaldron** [comment]
I just tried `npm i -g devsnek/esvu` and here's the outcome: 

```
JavaScriptCore ❯ Checking version...
JavaScriptCore ❯ Installing version 275913
JavaScriptCore ❯ Downloading https://s3-us-west-2.amazonaws.com/minified-archives.webkit.org/mac-catalina-x86_64-release/275913.zip
esvu ✖ Fatal error installing JavaScriptCore Error: Got 404
    at /Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/installer.js:67:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.install (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/installer.js:64:30)
    at async installEngine (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:121:3)
    at async i (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:149:7)
    at async updateAll (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:160:7)
    at async main (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:177:7)
```

(I have the same issue as @rbuckton and @QC-L, on Mac)

**Comment by rbuckton** [comment]
Still getting an error, though its' different now (same as the one @rwaldron received):

```sh
esvu ❯ version 1.2.3
JavaScriptCore ❯ Checking version...
JavaScriptCore ! There are external requirements that may need to be installed:
JavaScriptCore !   * WinCairoRequirements - https://github.com/WebKitForWindows/WinCairoRequirements
JavaScriptCore ❯ Installing version 276106
JavaScriptCore ❯ Downloading https://s3-us-west-2.amazonaws.com/archives.webkit.org/wincairo-x86_64-release/276106.zip
esvu ✖ Error: Got 404
    at C:\Users\rbuckton\AppData\Roaming\nvm\v15.4.0\node_modules\esvu\src\installer.js:67:17
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Function.install (C:\Users\rbuckton\AppData\Roaming\nvm\v15.4.0\node_modules\esvu\src\installer.js:64:30)
    at async installEngine (C:\Users\rbuckton\AppData\Roaming\nvm\v15.4.0\node_modules\esvu\src\bin.js:121:3)
    at async main (C:\Users\rbuckton\AppData\Roaming\nvm\v15.4.0\node_modules\esvu\src\bin.js:168:7)
esvu ✖ Some engines were not installed.
```

**Comment by rbuckton** [comment]
I think the issue is that the "latest" version is currently in progress and its build hasn't finished:
```json
{
  "builds": [
    {
      "builderid": 27,
      "buildid": 99633,
      "buildrequestid": 158208,
      "complete": false,
      "complete_at": null,
      ...
      "results": null,
      "started_at": 1618539252,
      "state_string": "building",
      "workerid": 31
    }
  ],
  "meta": {
    "total": 1
  }
}

**Comment by rbuckton** [comment]
Using a value higher than `limit=1` and walking backwards until you find a completed build might help.

**Comment by devsnek** [comment]
can someone confirm that this is fixed on the master branch?

**Comment by rwaldron** [comment]
@devsnek I've just confirmed that master works correctly. Sorry for the extended delay in responding.
