### ISSUE TITLE
Fatal error installing both GraalJS and XS (darwin-x64)

### ISSUE THREAD

**Issue by rwaldron** [devsnek/esvu#25]
v1.2.4

```
esvu ✖ Fatal error installing GraalJS TypeError: body.filter is not a function
    at Function.resolveVersion (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/engines/graaljs.js:39:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.install (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/installer.js:43:21)
    at async installEngine (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:121:3)
    at async i (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:149:7)
    at async updateAll (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:160:7)
    at async main (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:177:7)
```

```
esvu ✖ Fatal error installing XS TypeError: body.find is not a function
    at Function.resolveVersion (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/engines/xs.js:36:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.install (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/installer.js:43:21)
    at async installEngine (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:121:3)
    at async i (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:149:7)
    at async updateAll (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:160:7)
    at async main (/Users/rwaldron/.volta/tools/image/packages/esvu/lib/node_modules/esvu/src/bin.js:177:7)
```

**Comment by rwaldron** [comment]
I think you may be right, as I'm now able to run esvu and install all engines with no issue. 🤷
